/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import javax.swing.JOptionPane;

/**
 *
 * @author Long Nguyen Nhat
 */
public class ConfirmDiaglogs extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmDiaglogs
     */
    public ConfirmDiaglogs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnYesNo = new javax.swing.JButton();
        btnYesNoCancel = new javax.swing.JButton();
        btnOkCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnYesNo.setText("Yes - No");
        btnYesNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesNoActionPerformed(evt);
            }
        });

        btnYesNoCancel.setText("Yes - No - Cancel");
        btnYesNoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesNoCancelActionPerformed(evt);
            }
        });

        btnOkCancel.setText("OK - Cancel");
        btnOkCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnYesNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btnYesNoCancel)
                .addGap(125, 125, 125)
                .addComponent(btnOkCancel)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYesNo)
                    .addComponent(btnYesNoCancel)
                    .addComponent(btnOkCancel))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkCancelActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Ok cancel dialog",
                "yes - no", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn OK");
        } else if (result == JOptionPane.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn cancel");
        } else {
            return;
        }
    }//GEN-LAST:event_btnOkCancelActionPerformed

    private void btnYesNoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesNoCancelActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Yes no cancel dialog",
                "yes - no", JOptionPane.YES_NO_CANCEL_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn yes");
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn no");
        } else if (result == JOptionPane.CANCEL_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn cancel");
        } else {
            return;
        }
    }//GEN-LAST:event_btnYesNoCancelActionPerformed

    private void btnYesNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesNoActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Yes no dialog",
                "yes - no", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn yes");
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "bạn đã chọn no");
        } else {
            return;
        }
    }//GEN-LAST:event_btnYesNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmDiaglogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmDiaglogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmDiaglogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmDiaglogs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmDiaglogs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkCancel;
    private javax.swing.JButton btnYesNo;
    private javax.swing.JButton btnYesNoCancel;
    // End of variables declaration//GEN-END:variables
}
